-- 모든 레코드 조회하기
SELECT ANIMAL_ID, ANIMAL_TYPE, DATETIME, INTAKE_CONDITION, NAME, SEX_UPON_INTAKE FROM ANIMAL_INS ORDER BY ANIMAL_ID

-- 이름이 없는 동물의 아이디
SELECT ANIMAL_ID FROM ANIMAL_INS WHERE NAME IS NULL

-- 최댓값 구하기
SELECT MAX(DATETIME) FROM ANIMAL_INS

-- 입양 시각 구하기(1)
SELECT TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) AS HOUR, 
COUNT(TO_NUMBER(TO_CHAR(DATETIME, 'HH24'))) AS COUNT
FROM ANIMAL_OUTS 
GROUP BY TO_NUMBER(TO_CHAR(DATETIME, 'HH24'))
HAVING TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) >= 9 and 
TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) <= 19
ORDER BY HOUR

-- DATETIME에서 DATE로 형 변환
SELECT ANIMAL_ID, NAME, TO_CHAR(DATETIME, 'YYYY-MM-DD')
FROM ANIMAL_INS
ORDER BY ANIMAL_ID
