-- JOIN (LEFT JOIN)
-- SELECT
-- FROM 기준 테이블
-- LEFT JOIN 비교테이블 ON 비교값
-- WHERE 조건
-- ORDER  BY 순서

-- 없어진 기록 찾기
SELECT O.ANIMAL_ID, O.NAME 
FROM ANIMAL_OUTS as O
LEFT JOIN ANIMAL_INS as I 
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.ANIMAL_ID IS NULL
ORDER BY ANIMAL_ID
-- 있었는데요 없습니다.
SELECT I.ANIMAL_ID, I.NAME
FROM ANIMAL_INS as I
JOIN ANIMAL_OUTS as O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE O.DATETIME < I.DATETIME
ORDER BY I.DATETIME
-- 오랜기간 보호한 동물(1)
SELECT I.NAME, I.DATETIME
FROM ANIMAL_INS as I
LEFT JOIN ANIMAL_OUTS as O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE O.ANIMAL_ID IS NULL
ORDER BY I.DATETIME LIMIT 3
-- 오랜기간 보호한 동물 (2)
SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_OUTS as O
JOIN ANIMAL_INS as I
ON I.ANIMAL_ID = O.ANIMAL_ID
ORDER BY O.DATETIME - I.DATETIME DESC
LIMIT 2

--헤비 유저가 소유한 장소
-- Kaka0
SELECT ID, NAME, HOST_ID
FROM PLACES 
WHERE HOST_ID IN 
(
    SELECT HOST_ID FROM PLACES
    GROUP BY HOST_ID  
    HAVING COUNT(ID) >= 2
)
ORDER BY ID
