SELECT G.USER_ID, IF (P.TOTAL_PRICE IS NULL, 0, P.TOTAL_PRICE)
FROM GAME_USER
JOIN
(
  SELECT USER_ID, SUM(PRICE) AS TOTAL_PRICE
  FROM PAYMENTS
  GROUP BY USER_ID
) AS P
ON G.USER_ID = P.USER_ID
ORDER BY G.USER_ID
